# Define the Workflow Name
name: CI/CD Pipeline

# Define triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./frontend

      - name: Build React app
        run: npm run build
        working-directory: ./frontend

  # Job for building and testing the backend
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Run tests
        run: python -m unittest discover
        working-directory: ./backend

  # Job for building and pushing Docker images
  docker:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend Docker image
        run: docker build -t <dockerhub_username>/frontend:latest ./frontend

      - name: Build backend Docker image
        run: docker build -t <dockerhub_username>/backend:latest ./backend

      - name: Push frontend Docker image
        run: docker push <dockerhub_username>/frontend:latest

      - name: Push backend Docker image
        run: docker push <dockerhub_username>/backend:latest

  # OPTIONAL: Deployment job
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: ./deploy.sh # Replace with your deployment script or commands
